### ISSUE TITLE
7.7 加入Quartz 报错

### ISSUE THREAD

**Issue by f0en1x-1894** [wendal/nutz-book#2]
quartz.properties中缺少配置项：

```
org.quartz.threadPool.class = org.quartz.simpl.SimpleThreadPool
```

导致启动时报错：

```
Caused by: org.quartz.SchedulerException: ThreadPool class not specified. 
    at org.quartz.impl.StdSchedulerFactory.instantiate(StdSchedulerFactory.java:759)
    at org.quartz.impl.StdSchedulerFactory.getScheduler(StdSchedulerFactory.java:1371)
    at org.quartz.impl.StdSchedulerFactory.getDefaultScheduler(StdSchedulerFactory.java:1387)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at org.nutz.lang.born.MethodBorning.born(MethodBorning.java:17)
    ... 61 more
```

**Comment by f0en1x-1894** [comment]
好吧，是Quartz版本弄错了。。。

**Comment by wendal** [comment]
呵呵,新版有默认值
